
/**
* AUTOGENERATED BY convert.py
* DO NOT EDIT THIS FILE!
*
* IF MODIFICATIONS NEED TO BE MADE, MODIFY can_data.txt!
*
* CAN Defintiion for ECU 'PTS'
*/

#ifdef EGS_SPRINTER_MODE

#ifndef __ECU_PTS_H_
#define __ECU_PTS_H_

#include <stdint.h>
    



class ECU_PTS {
	public:
        /**
         * @brief Imports the CAN frame given the CAN ID, CAN Contents, and current timestamp
         *
         * Returns true if the frame was imported successfully, and false if import failed (Due to non-matching CAN ID).
         *
         * NOTE: The endianness of the value cannot be guaranteed. It is up to the caller to correct the byte order!
         */
        bool import_frames(uint64_t value, uint32_t can_id, uint64_t timestamp_now) {
            switch(can_id) {
                default:
                    return false;
            }
        }
        
	private:
		uint64_t FRAME_DATA[0];
		uint64_t LAST_FRAME_TIMES[0];
};
#endif // __ECU_PTS_H_

#endif // EGS_SPRINTER_MODE