#ifndef __NVS_ALL_KEYS_H_
#define __NVS_ALL_KEYS_H_

#define CREATE_NAME_EXTERN(def, str) extern const char* NVS_KEY_##def;

#define FOR_LIST(DO) \
    /* -- MISC CORE KEYS -- */ \
    DO(CORE_SCN , "CORE_SCN")\
    DO(DEV_MODE , "DEV_MODE")\
    DO(LAST_PROFILE, "LAST_PROFILE")\
    DO(LAST_FW, "LAST_FW")\
    /* -- MAP NAMES -- */ \
    DO(MAP_NAME_S_DIESEL_UPSHIFT , "S_DIESEL_UP")\
    DO(MAP_NAME_S_DIESEL_DOWNSHIFT , "S_DIESEL_DOWN")\
    DO(MAP_NAME_S_PETROL_UPSHIFT , "S_PETROL_UP")\
    DO(MAP_NAME_S_PETROL_DOWNSHIFT , "S_PETROL_DOWN")\
    DO(MAP_NAME_C_DIESEL_UPSHIFT , "C_DIESEL_UP")\
    DO(MAP_NAME_C_DIESEL_DOWNSHIFT , "C_DIESEL_DOWN")\
    DO(MAP_NAME_C_PETROL_UPSHIFT , "C_PETROL_UP")\
    DO(MAP_NAME_C_PETROL_DOWNSHIFT , "C_PETROL_DOWN")\
    DO(MAP_NAME_A_DIESEL_UPSHIFT , "A_DIESEL_UP")\
    DO(MAP_NAME_A_DIESEL_DOWNSHIFT , "A_DIESEL_DOWN")\
    DO(MAP_NAME_A_PETROL_UPSHIFT , "A_PETROL_UP")\
    DO(MAP_NAME_A_PETROL_DOWNSHIFT , "A_PETROL_DOWN")\
    DO(MAP_NAME_M_DIESEL_UPSHIFT , "M_DIESEL_UP")\
    DO(MAP_NAME_M_DIESEL_DOWNSHIFT , "M_DIESEL_DOWN")\
    DO(MAP_NAME_M_PETROL_UPSHIFT, "M_PETROL_UP")\
    DO(MAP_NAME_M_PETROL_DOWNSHIFT , "M_PETROL_DOWN")\
    DO(MAP_NAME_FILL_TIME, "FILL_T")\
    DO(MAP_NAME_TCC_PWM , "TCC_PWM")\
    DO(MAP_NAME_FILL_PRESSURE , "FILL_PRESS_3")\
    DO(MAP_NAME_FILL_LOW_PRESSURE , "FILL_LPRESS_4")\
    DO(MAP_NAME_M_UPSHIFT_TIME , "M_UPSHIFT_TIME")\
    DO(MAP_NAME_M_DOWNSHIFT_TIME , "M_DNSHIFT_TIME")\
    DO(MAP_NAME_C_UPSHIFT_TIME , "C_UPSHIFT_TIME")\
    DO(MAP_NAME_C_DOWNSHIFT_TIME , "C_DNSHIFT_TIME")\
    DO(MAP_NAME_S_UPSHIFT_TIME , "S_UPSHIFT_TIME")\
    DO(MAP_NAME_S_DOWNSHIFT_TIME , "S_DNSHIFT_TIME")\
    DO(MAP_NAME_A_UPSHIFT_TIME , "A_UPSHIFT_TIME")\
    DO(MAP_NAME_A_DOWNSHIFT_TIME , "A_DNSHIFT_TIME")\
    DO(MAP_NAME_W_UPSHIFT_TIME , "W_UPSHIFT_TIME")\
    DO(MAP_NAME_W_DOWNSHIFT_TIME , "W_DNSHIFT_TIME")\
    DO(MAP_NAME_R_UPSHIFT_TIME , "R_UPSHIFT_TIME")\
    DO(MAP_NAME_R_DOWNSHIFT_TIME , "R_DNSHIFT_TIME")\
    DO(TCC_ADAPT_SLIP_MAP,"TCC_S_ADAPT_3")\
    DO(TCC_ADAPT_LOCK_MAP,"TCC_L_ADAPT_3")\
    DO(TCC_SLIP_TARGET_MAP,"TCC_RPM_3")\
    DO(MAP_NAME_ADAPT_PREFILL_TIME , "ADP_PT_A2")\
    DO(MAP_NAME_ADAPT_SPC_OFFSET, "ADP_SO_A0")\
    DO(MAP_NAME_ADAPT_FREEING_TRQ, "ADP_FR_A0")\
    DO(MAP_NAME_ADAPT_APPLYING_TRQ, "ADP_AP_A1")\
    /* SUBSYSTEM SETTINGS */ \
    DO(TCC_SETTINGS, "TCC_AB")\
    DO(SOL_SETTINGS, "SOL_A0")\
    DO(SBS_SETTINGS, "SBS_A6")\
    DO(PRM_SETTINGS, "PRM_A3")\
    DO(ADP_SETTINGS, "ADP_A2")\
    DO(ETS_SETTINGS, "ETS_A3")\
    DO(REL_SETTINGS, "REL_A3")\
    DO(GAR_SETTINGS, "GAR_A3")\
    DO(CRS_SETTINGS, "CRS_A2")\
    DO(SHIFT_POINTS_S, "SPS_A1")\
    DO(SHIFT_POINTS_C, "SPC_A1")\
    DO(SHIFT_POINTS_A, "SPA_A1")\
    /* HFM ENGINE DATA */ \
    DO(MAP_NAME_HFM_ENGINE_TORQUE, "HFM_TORQUE_MAP")\
    DO(MAP_NAME_HFM_ENGINE_MASS_AIR_FLOW, "HFM_MAF_MAP")\
    DO(MAP_NAME_HFM_ENGINE_MAX_MASS_AIR_FLOW, "HFM_MAX_MAF_MAP")\

extern const char** ALL_NVS_KEYS[];

extern int ALL_NVS_KEYS_LEN;

FOR_LIST(CREATE_NAME_EXTERN)

#endif

