
/**
* AUTOGENERATED BY convert.py
* DO NOT EDIT THIS FILE!
*
* IF MODIFICATIONS NEED TO BE MADE, MODIFY can_data.txt!
*
* CAN Defintiion for ECU 'BRAKES'
*/

#ifndef ECU_BRAKES_H
#define ECU_BRAKES_H

#include <stdint.h>
    



class ECU_BRAKES {
	public:
        /**
         * @brief Imports the CAN frame given the CAN ID, CAN Contents, and current timestamp
         *
         * Returns true if the frame was imported successfully, and false if import failed (Due to non-matching CAN ID).
         *
         * NOTE: The endianness of the value cannot be guaranteed. It is up to the caller to correct the byte order!
         */
         static bool import_frames(uint64_t value, uint32_t can_id, uint32_t timestamp_now) {
            bool add = true;
            return add;
        }
        
	private:
		uint64_t FRAME_DATA[0] = { };
		uint32_t LAST_FRAME_TIMES[0] = { };
};
#endif // ECU_BRAKES_H