#ifndef FS_340H_H_
#define FS_340H_H_

/**
 * AUTOGENERATED BY gen_unions.py
*/
#include <stdint.h>

#define FS_340_ID 0x0340






typedef union {
    uint8_t bytes[8];
    uint64_t raw;

    // Sets Load torque ABC pump
    void set_M_LAST(uint8_t value){ raw = (raw & 0xfffffffffffffff0) | ((uint64_t)value & 0xf) << 0; }
    // Gets Load torque ABC pump
    uint8_t get_M_LAST() { return raw >> 0 & 0xf; }

    /** Imports the frame data from a source */
    void import_frame(uint32_t cid, uint8_t* data, uint8_t len) {
        if (cid == FS_340_ID) {
            for (int i = 0; i < len; i++) {
                bytes[7-i] = data[i];
            }
        }
    }

    /** Exports the frame data to a destination */
    void export_frame(uint32_t* cid, uint8_t* data, uint8_t* len) {
        *cid = FS_340_ID;
        *len = 8;
        for (int i = 0; i < *len; i++) {
            data[i] = bytes[7-i];
        }
    }
} FS_340;

#endif
