name: Remote deploy code documentation

on:
  push:
    branches: ["dev", "main"]


env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Install doxygen
        run: sudo apt-get update && sudo apt-get install doxygen
      - name: Build documentation
        run: doxygen
      - name: Deploy docs
        uses: garygrossgarten/github-action-scp@release
        with:
          local: html
          remote: /var/www/html/${{ env.BRANCH_NAME }}
          user: ${{ secrets.SSH_USER }}
          host: ${{ secrets.HOST }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          rmRemote: true

