name: Remote deploy code documentation

on:
  push:
    branches: ["dev", "main"]
    
jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Apt update
        run: sudo apt-get update
      - name: Install doxygen
        run: sudo apt-get install doxygen
      - name: Install graphviz
        run: sudo apt-get install graphviz
      - name: Build documentation
        run: doxygen
      - name: Deploy docs
        uses: garygrossgarten/github-action-scp@release
        with:
          local: html
          remote: /var/www/html/${{ env.GITHUB_REF_NAME }}
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.HOST }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          rmRemote: true

